import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Providers } from './providers';


const ChangaBold = localFont({
  src: './fonts/shadows/Changa-Bold.ttf',
  variable: '--font-Changa-Bold',
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={` ${ChangaBold.variable}  antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}


